Files migrated to U250 and confirmed working on Azure

diff --git a/cosinesim/Makefile b/cosinesim/Makefile
--- a/cosinesim/Makefile
+++ b/cosinesim/Makefile
@@ -26,16 +26,8 @@ PRODUCT_VER=$(strip $(shell cat VERSION))
 #all: javaApi cppBuild javaTest stage
 all: stage
 
-#
-# Global Definitions
-#
-
-# Location of graphanalytics project
-GRAPH_ANALYTICS_DIR = ..
-
-# General output directory for intermediate build artifacts
-BUILD_DIR = build
-
+# Common targets for all products (packaging)
+include ../common/Makefile-common.mk
 
 #######################################################################################################################
 #
@@ -88,6 +80,7 @@ INCLUDES_libCosineSim = \
 	-I$(GRAPH_ANALYTICS_DIR)/L2/include \
 	-I$(GRAPH_ANALYTICS_DIR)/L3/include \
 	-I$(GRAPH_ANALYTICS_DIR)/ext \
+	-I$(GRAPH_ANALYTICS_DIR)/common/include \
 	-I$(GRAPH_ANALYTICS_DIR)/ext/xcl2 \
 	-Iinclude
 #	-I${JAVA_HOME}/include \
@@ -95,10 +88,12 @@ INCLUDES_libCosineSim = \
 
 LDLIBS_libCosineSim = \
 	
-LIB_SHORT_NAME = XilinxCosineSim
+LIB_SHORT_NAME = AMDCosineSim
 LIB_NAME = lib$(LIB_SHORT_NAME).so
-LOADER_SHORT_NAME = XilinxCosineSim_loader
+LOADER_SHORT_NAME = AMDCosineSim_loader
 LOADER_NAME = lib$(LOADER_SHORT_NAME).a
+LIB_STATIC_SHORT_NAME = AMDCosineSimStatic
+LIB_STATIC_NAME = lib$(LIB_STATIC_SHORT_NAME).so
 
 #SRCS_L3 = $(wildcard $(GRAPH_ANALYTICS_DIR)/L3/src/*.cpp) $(GRAPH_ANALYTICS_DIR)/ext/xcl2/xcl2.cpp
 
@@ -126,13 +121,27 @@ OBJS_libCosineSim = $(OBJS_L3) $(OBJS_top)
 CPP_DOXY_TARGET_DIR = $(BUILD_DIR)/cppdocs
 CPP_DOXY_TRIGGER_FILE = $(CPP_DOXY_TARGET_DIR)/html/index.html
 
+XRMLIB_DIR = $(GRAPH_ANALYTICS_DIR)/xrmlib
+XRMLIB_LIB_SHORT_NAME = XilinxXrmLib
+XRMLIB_LIB_NAME = lib$(XRMLIB_LIB_SHORT_NAME).a
+XRMLIB_LIB_PATH = $(XRMLIB_DIR)/$(CPP_BUILD_DIR)/$(XRMLIB_LIB_NAME)
+
+XRTICD_LIB_NAME = libxilinxopencl.so
+XRTICD_ICD_DIR_NAME = icd
+XRTICD_LIB_PATH = $(CPP_BUILD_DIR)/$(XRTICD_ICD_DIR_NAME)/$(XRTICD_LIB_NAME)
+
 .PHONY: cppBuild cppBuild2
 
 # Make in a child process so that we can isolate the run that includes automatic header dependencies
 cppBuild: $(CPP_BUILD_DIR)
 	@make cppBuild2
 
-cppBuild2: $(CPP_BUILD_DIR)/$(LIB_NAME) $(CPP_BUILD_DIR)/$(LOADER_NAME)
+#	@cd $(XRMLIB_DIR); make DEBUG=$(DEBUG)
+
+cppBuild2: $(CPP_BUILD_DIR)/$(LIB_NAME)
+	
+#	$(CPP_BUILD_DIR)/$(LIB_STATIC_NAME) $(CPP_BUILD_DIR)/$(LOADER_NAME) \
+#	$(XRTICD_LIB_PATH)
 
 
 # Create the target directory (if needed)
@@ -141,17 +150,58 @@ $(CPP_BUILD_DIR):
 
 # .so
 
-LIB_DEPS = -L$(XILINX_XRT)/lib -lOpenCL -lpthread -lrt -Wno-unused-label -Wno-narrowing -DVERBOSE -L$(XILINX_XRM)/lib -lxrm
+# Library dependencies for building the .so's
+
+LIB_BUILD_DEPS = -L$(XILINX_XRT)/lib -lOpenCL -lpthread -lrt -Wno-unused-label -Wno-narrowing -DVERBOSE
 
 ifeq ($(MEMALLOC),tcmalloc)
-    LIB_DEPS += -ltcmalloc
+    LIB_BUILD_DEPS += -ltcmalloc
 endif
+
+LIB_STATIC_BUILD_DEPS = $(LIB_BUILD_DEPS) -L$(XRMLIB_DIR)/$(CPP_BUILD_DIR) -l$(XRMLIB_LIB_SHORT_NAME) -luuid
+LIB_DYNAMIC_BUILD_DEPS = $(LIB_BUILD_DEPS) -L$(XILINX_XRM)/lib -lxrm
+
+# Library dependencies for any executable linking with the .so
+
+LIB_STATIC_RUN_DEPS = $(LIB_BUILD_DEPS) -L $(CPP_BUILD_DIR) -l$(LIB_STATIC_SHORT_NAME) -ldl
+LIB_DYNAMIC_RUN_DEPS = $(LIB_DYNAMIC_BUILD_DEPS) -L $(CPP_BUILD_DIR) -l$(LIB_SHORT_NAME)
+LIB_LOADER_RUN_DEPS = $(LIB_BUILD_DEPS) -ldl
 
 # SHAREDLIB_FLAGS_libCosineSim = -shared
 SHAREDLIB_FLAGS_libCosineSim = -fPIC -rdynamic -shared -w -Wl,--export-dynamic
 
 $(CPP_BUILD_DIR)/$(LIB_NAME): $(OBJS_libCosineSim) $(DEPLIBS_libCosineSim)
-	$(LINK.cc) -o $@ $(OBJS_libCosineSim) $(SHAREDLIB_FLAGS_libCosineSim) $(LDLIBS_libCosineSim) $(LIB_DEPS)
+	$(LINK.cc) -o $@ $(OBJS_libCosineSim) $(SHAREDLIB_FLAGS_libCosineSim) $(LDLIBS_libCosineSim) \
+	    $(LIB_DYNAMIC_BUILD_DEPS)
+	    
+# Static .so
+
+LOCAL_XRT = $(GRAPH_ANALYTICS_DIR)/ext/XRT
+LOCAL_XRT_BOOST_DIR = $(LOCAL_XRT)/boost/xrt/lib
+LOCAL_XRT_BOOST_LIB_NAMES = \
+    libboost_filesystem-mt-x64.a \
+    libboost_program_options-mt-x64.a \
+    libboost_system-mt-x64.a
+LOCAL_XRT_BOOST_LIBS = $(addprefix $(LOCAL_XRT_BOOST_DIR)/,$(LOCAL_XRT_BOOST_LIB_NAMES))
+
+LOCAL_XRT_LIB_DIR = $(LOCAL_XRT)/build/$(CPP_BUILD_DIR)/opt/xilinx/xrt/lib
+LOCAL_XRT_LIB_NAMES = libxrt++_static.a libxrt_core_static.a libxrt_coreutil_static.a libxrt_swemu.so
+LOCAL_XRT_LIBS = $(addprefix $(LOCAL_XRT_LIB_DIR)/,$(LOCAL_XRT_LIB_NAMES))
+
+
+$(CPP_BUILD_DIR)/$(LIB_STATIC_NAME): $(OBJS_libCosineSim) $(DEPLIBS_libCosineSim) $(XRMLIB_LIB_PATH)
+	$(LINK.cc) -o $@ $(OBJS_libCosineSim) -static-libgcc -static-libstdc++ -Wl,-Bsymbolic \
+	$(SHAREDLIB_FLAGS_libCosineSim) $(LDLIBS_libCosineSim) $(LIB_STATIC_BUILD_DEPS) $(LOCAL_XRT_LIBS) \
+	$(LOCAL_XRT_BOOST_LIBS) $(LIB_STATIC_BUILD_DEPS)
+
+# Xilinx OpenCL Installable Client Driver
+
+#$(XRTICD_LIB_PATH): $(LOCAL_XRT_LIB_DIR)/libxilinxopencl_static.a
+#	mkdir -p $(CPP_BUILD_DIR)/$(XRTICD_ICD_DIR_NAME)
+#	g++ -std=gnu++14 -o $@ -static-libgcc -static-libstdc++ -Wl,-Bsymbolic $(SHAREDLIB_FLAGS_libCosineSim) \
+#	-Wl,--whole-archive $< -Wl,--no-whole-archive $(LOCAL_XRT_LIBS) -ldl -luuid $(LOCAL_XRT_BOOST_LIBS) -lpthread
+
+# /usr/lib/x86_64-linux-gnu/libboost_filesystem.a 
 
 # loader .a
 
@@ -218,7 +268,7 @@ PYTHON_DIR = /usr/include/$(PYTHON)
 PYTHONENV_NAME = pyvenv
 PYTHONENV = ./$(PYTHONENV_NAME)/bin/$(PYTHON)
 PYTHON_API_DIR = wrappers/python
-PYTHON_LIB_NAME := xilCosineSim.so #$(shell python-config --extension-suffix)
+PYTHON_LIB_NAME := amdCosineSim.so #$(shell python-config --extension-suffix)
 
 SRC_FILE_NAMES_python = pythonapi.cpp
 
@@ -298,7 +348,8 @@ LDLIBS_test = \
 	
 
 SRC_FILE_NAMES_test = \
-    cosinesim_test.cpp 
+    cosinesim_test.cpp \
+    icdtest.cpp
 
 SRCS_test = $(addprefix $(TEST_DIR)/,$(SRC_FILE_NAMES_test))
 OBJS_test = $(addprefix $(CPP_BUILD_DIR)/,$(notdir $(SRCS_test:.cpp=.o)))
@@ -307,7 +358,11 @@ DEPS_test = $(OBJS_test:.o=.d)
 # List of all test executables to build
 EXEC_FILE_NAMES_test = \
     cosinesim_test \
-    cosinesim_dyn_test 
+
+
+#    cosinesim_test_loader \
+#    cosinesim_test_static \
+#    icdtest \
 
 EXECS_test = $(addprefix $(CPP_BUILD_DIR)/,$(EXEC_FILE_NAMES_test))
 
@@ -321,18 +376,33 @@ cppTest2: $(EXECS_test)
 
 # Test executables
 
-LDFLAGS_test = -fPIC -w -L $(CPP_BUILD_DIR) -l$(LIB_SHORT_NAME)
+# With original dynamic cosinesim .so
+LDFLAGS_test = -fPIC -w
 
+# Using static cosinesim .so
+LDFLAGS_static_test = -fPIC -L $(CPP_BUILD_DIR) -l$(LIB_STATIC_SHORT_NAME)
+
+# With original dynamic cosinesim .so
 $(CPP_BUILD_DIR)/cosinesim_test: $(CPP_BUILD_DIR)/cosinesim_test.o $(CPP_BUILD_DIR)/$(LIB_NAME)
-	$(LINK.cc) -o $@ $< $(LDFLAGS_test) $(LIB_DEPS)
+	$(LINK.cc) -o $@ $< $(LDFLAGS_test) $(LIB_DYNAMIC_RUN_DEPS)
 
-$(CPP_BUILD_DIR)/cosinesim_dyn_test: $(CPP_BUILD_DIR)/cosinesim_test.o $(CPP_BUILD_DIR)/$(LOADER_NAME) $(CPP_BUILD_DIR)/$(LIB_NAME)
-	$(LINK.cc) -o $@ $< -fPIC -w -L $(CPP_BUILD_DIR) -l$(LOADER_SHORT_NAME) -ldl $(LIB_DEPS)
+# Version using static cosinesim .so.  Not working for now, seems to produce bad results
+#$(CPP_BUILD_DIR)/cosinesim_test_static: $(CPP_BUILD_DIR)/cosinesim_test.o $(CPP_BUILD_DIR)/$(LIB_STATIC_NAME)
+#	$(LINK.cc) -o $@ $< $(LDFLAGS_test) $(LIB_STATIC_RUN_DEPS)
+
+
+# Temporary test to check validity of Xilinx ICD built statically
+#$(CPP_BUILD_DIR)/icdtest: $(CPP_BUILD_DIR)/icdtest.o $(CPP_BUILD_DIR)/$(LIB_STATIC_NAME)
+#	$(LINK.cc) -o $@ $< -lstdc++ $(LDFLAGS_test) $(LIB_STATIC_BUILD_DEPS) $(XRTICD_LIB_PATH)
+
+# Problem with missing XRT symbols that are OCL related
+#$(CPP_BUILD_DIR)/cosinesim_test_loader: $(CPP_BUILD_DIR)/cosinesim_test.o $(CPP_BUILD_DIR)/$(LOADER_NAME) $(CPP_BUILD_DIR)/$(LIB_STATIC_NAME)
+#	$(LINK.cc) -o $@ $< $(LDFLAGS_test) $(CPP_BUILD_DIR)/$(LOADER_NAME) $(LIB_LOADER_RUN_DEPS)
 
 ###############################################################################
 # Parameters and targets for running tests
 numDevices=1
-deviceNames=xilinx_u50_gen3x16_xdma_201920_3
+deviceNames=u50
 testNum=-1
 numResults=-1
 verbose=0
@@ -341,12 +411,14 @@ ifneq ($(verbose),0)
   verboseFlag=-v
 endif
 
-ifeq ($(deviceNames),xilinx_u50_gen3x16_xdma_201920_3)
+ifeq ($(deviceNames),u50)
     XCLBIN_RUN = $(CURDIR)/staging/xclbin/$(XCLBIN_INSTALLED_NAME_U50)
-else ifeq ($(deviceNames),xilinx_u55c_gen3x16_xdma_base_2)
+else ifeq ($(deviceNames),u55c)
     XCLBIN_RUN = $(CURDIR)/staging/xclbin/$(XCLBIN_INSTALLED_NAME_U55C)
-else ifeq ($(deviceNames), xilinx_aws-vu9p-f1_shell-v04261818_201920_2)
+else ifeq ($(deviceNames),aws-f1)
     XCLBIN_RUN = $(CURDIR)/staging/xclbin/$(XCLBIN_INSTALLED_NAME_F1)
+else ifeq ($(deviceNames),u200)
+    XCLBIN_RUN = $(CURDIR)/staging/xclbin/$(XCLBIN_INSTALLED_NAME_U200)
 endif
 
 run: stage cppTest
@@ -356,9 +428,20 @@ run: stage cppTest
 	LD_LIBRARY_PATH=$(PWD)/$(CPP_BUILD_DIR):$$LD_LIBRARY_PATH $(CPP_BUILD_DIR)/cosinesim_test \
 	    -d $(numDevices) --xclbin $(XCLBIN_RUN) -t $(deviceNames) -1 $(testNum) -n $(numResults) $(verboseFlag)
 
-run-dyn-test: cppTest
-	LD_PRELOAD=$(PWD)/$(CPP_BUILD_DIR)/$(LIB_NAME) LD_LIBRARY_PATH=$(PWD)/$(CPP_BUILD_DIR):$(LD_LIBRARY_PATH) \
-	    $(CPP_BUILD_DIR)/cosinesim_dyn_test $(numDevices)
+#run-static: cppTest
+#	set -e; \
+#	. $(XILINX_XRT)/setup.sh && \
+##	LD_PRELOAD=$(PWD)/$(XRTICD_LIB_PATH) \
+#	LD_LIBRARY_PATH=$(PWD)/$(CPP_BUILD_DIR):$(PWD)/$(CPP_BUILD_DIR)/$(XRTICD_ICD_DIR_NAME):$$LD_LIBRARY_PATH \
+#	    $(CPP_BUILD_DIR)/cosinesim_test_static \
+#	    -d $(numDevices) -t $(deviceNames) -1 $(testNum) -n $(numResults) $(verboseFlag)
+
+run-loader: cppTest
+	LD_LIBRARY_PATH=$(PWD)/$(CPP_BUILD_DIR):$(LD_LIBRARY_PATH) $(CPP_BUILD_DIR)/cosinesim_test_loader \
+	    -d $(numDevices)
+
+run-staging-cpp: cppTest stage
+	cd staging/examples/cpp && make run deviceNames=$(deviceNames)
 
 # Macro to create a .o rule and a .d rule for each .cpp
 
@@ -408,7 +491,7 @@ L2_TOP_DIR_4PU = $(GRAPH_ANALYTICS_DIR)/L2/dense_similarity_multi_kernel_4pu
 XCLBIN_NAME_4PU = denseSimilarityKernel4PUWithAlias.xclbin
 XCLBIN_FILE_U55C = $(L2_BUILD_DIR_U55C)/$(XCLBIN_NAME_4PU)
 XCLBIN_INSTALLED_NAME_U55C = cosinesim_32bit_4pu_xilinx_u55c_gen3x16_xdma_base_2.xclbin
-XCLBIN_INSTALLED_U55C = /opt/xilinx/apps/graphanalytics/cosinesim/$(PRODUCT_VER)/xclbin/$(XCLBIN_INSTALLED_NAME_U55C)
+XCLBIN_INSTALLED_U55C = /opt/amd/apps/agml/cosinesim/$(PRODUCT_VER)/xclbin/$(XCLBIN_INSTALLED_NAME_U55C)
 
 # F1 XCLBIN 
 L2_TOP_DIR_F1 = $(GRAPH_ANALYTICS_DIR)/L2/dense_similarity_multi_kernel
@@ -417,8 +500,16 @@ L2_BUILD_DIR_F1 = $(L2_TOP_DIR_F1)/build_dir.hw.$(L2_XDEVICE_F1)
 XCLBIN_NAME_F1 = denseSimilarityKernel.awsxclbin 
 XCLBIN_FILE_F1 = $(L2_BUILD_DIR_F1)/$(XCLBIN_NAME_F1)
 XCLBIN_INSTALLED_NAME_F1 = cosinesim_xilinx_aws-vu9p-f1_shell-v04261818_201920_2.awsxclbin
-XCLBIN_INSTALLED_F1 =/opt/xilinx/apps/graphanalytics/cosinesim/$(PRODUCT_VER)/xclbin/$(XCLBIN_INSTALLED_NAME_F1)
+XCLBIN_INSTALLED_F1 =/opt/amd/apps/agml/cosinesim/$(PRODUCT_VER)/xclbin/$(XCLBIN_INSTALLED_NAME_F1)
 
+#U200 
+L2_TOP_DIR_U200 = $(GRAPH_ANALYTICS_DIR)/L2/dense_similarity_multi_kernel
+L2_XDEVICE_U200 = xilinx_u200_gen3x16_xdma_2_202110_1
+L2_BUILD_DIR_U200 = $(L2_TOP_DIR_U200)/build_dir.hw.$(L2_XDEVICE_U200)
+XCLBIN_NAME_U200 = denseSimilarityKernel.xclbin
+XCLBIN_FILE_U200 = $(L2_BUILD_DIR_U200)/$(XCLBIN_NAME_U200)
+XCLBIN_INSTALLED_NAME_U200 = cosinesim_xilinx_u200_gen3x16_xdma_2_202110_1.xclbin
+XCLBIN_INSTALLED_U200 =/opt/amd/apps/agml/cosinesim/$(PRODUCT_VER)/xclbin/$(XCLBIN_INSTALLED_NAME_U200)
 DEVICE ?= $(L2_XDEVICE)
 ifeq ($(findstring u55, $(DEVICE)), u55)
 	XCLBIN_BUILD_DIR=$(L2_TOP_DIR_4PU)
@@ -470,6 +561,18 @@ $(XCLBIN_FILE_F1):
 	    echo "2. Do 'make xclbin' and go for a very long coffee break.  (Recommended for build automation)"; \
 	    false; \
 	fi
+
+$(XCLBIN_FILE_U200):
+	@if [ -r $(XCLBIN_INSTALLED_U200) ]; then \
+	    echo "INFO: The XCLBIN file $(XCLBIN_FILE_U200) is missing.  Copying from installed area."; \
+	    cp -r $(XCLBIN_INSTALLED_U200) $@; \
+	else \
+	    echo "ERROR: The XCLBIN file $(XCLBIN_FILE_U200) is missing."; \
+	    echo "Because building an XCLBIN file can be an all-day proposition, you have two choices for completing this build:"; \
+	    echo "1. Copy a pre-built XCLBIN to the target location above.  (Recommended for developers)"; \
+	    echo "2. Do 'make xclbin' and go for a very long coffee break.  (Recommended for build automation)"; \
+	    false; \
+	fi
 #######################################################################################################################
 #
 # Staging
@@ -490,16 +593,19 @@ $$(STAGE_DIR)/$(1): $(1)
 endef
 $(foreach f,$(STAGE_COPY_FILES),$(eval $(call STAGE_COPY_RULE,$(f))))
 
-STAGE_XILINX_APPS_COMMON = $(STAGE_DIR)/include/xilinx_apps_common.hpp
-XILINX_APPS_COMMON = $(GRAPH_ANALYTICS_DIR)/ext/xilinx_apps_common.hpp
-$(STAGE_XILINX_APPS_COMMON): $(XILINX_APPS_COMMON)
-	cp -f $^ $@
+#STAGE_XILINX_APPS_COMMON = $(STAGE_DIR)/include/xilinx_apps_common.hpp
+#XILINX_APPS_COMMON = $(GRAPH_ANALYTICS_DIR)/ext/xilinx_apps_common.hpp
+#$(STAGE_XILINX_APPS_COMMON): $(XILINX_APPS_COMMON)
+#	cp -f $^ $@
 
 # Binary (C++) files
 
 STAGE_LIB_FILES = \
-    $(LIB_NAME) \
-    $(LOADER_NAME)
+    $(LIB_NAME)
+
+#    $(XRTICD_ICD_DIR_NAME)/$(XRTICD_LIB_NAME)
+#    $(LIB_STATIC_NAME) \
+#    $(LOADER_NAME) \
 
 ifneq ($(wildcard $(CPP_BUILD_DIR)/$(PYTHON_LIB_NAME)),)
     STAGE_LIB_FILES += $(PYTHON_LIB_NAME)
@@ -510,6 +616,7 @@ $$(STAGE_DIR)/lib/$(1): $$(CPP_BUILD_DIR)/$(1)
 	cp -f $$^ $$@
 endef
 $(foreach f,$(STAGE_LIB_FILES),$(eval $(call STAGE_LIB_RULE,$(f))))
+
 
 # Example files - need to be zipped up
 
@@ -536,6 +643,7 @@ stage-examples: $(STAGE_EXAMPLE_FILES)
 	@make fill-example-stage
 
 fill-example-stage: $(STAGE_STAGED_EXAMPLE_FILES)
+	cp VERSION $(STAGE_DIR)/examples/
 	
 $(STAGE_STAGED_EXAMPLE_FILES):
 	cp -f $(patsubst $(STAGE_DIR)/%,%,$@) $@
@@ -549,11 +657,16 @@ STAGE_XCLBIN_FILE_U50 = $(STAGE_DIR)/xclbin/$(STAGE_XCLBIN_NAME_U50)
 STAGE_XCLBIN_NAME_F1 = $(XCLBIN_INSTALLED_NAME_F1)
 STAGE_XCLBIN_FILE_F1 = $(STAGE_DIR)/xclbin/$(STAGE_XCLBIN_NAME_F1)
 
+STAGE_XCLBIN_NAME_U200 = $(XCLBIN_INSTALLED_NAME_U200)
+STAGE_XCLBIN_FILE_U200 = $(STAGE_DIR)/xclbin/$(STAGE_XCLBIN_NAME_U200)
 
 $(STAGE_XCLBIN_FILE_U50): $(XCLBIN_FILE_U50)
 	cp -f $^ $@
 
 $(STAGE_XCLBIN_FILE_F1): $(XCLBIN_FILE_F1)
+	cp -f $^ $@
+
+$(STAGE_XCLBIN_FILE_U200): $(XCLBIN_FILE_U200)
 	cp -f $^ $@
 
 STAGE_XCLBIN_NAME_U55C = $(XCLBIN_INSTALLED_NAME_U55C)
@@ -564,15 +677,17 @@ $(STAGE_XCLBIN_FILE_U55C): $(XCLBIN_FILE_U55C)
 
 # Top-level packaging rule
 
-STAGE_SUBDIR_NAMES = include lib src xclbin
+STAGE_SUBDIR_NAMES = include lib lib/$(XRTICD_ICD_DIR_NAME) src xclbin
 STAGE_SUBDIRS = $(addprefix $(STAGE_DIR)/,$(STAGE_SUBDIR_NAMES))
 STAGE_ALL_FILES = \
+    $(STAGE_COPY_COMMON_FILES) \
     $(addprefix $(STAGE_DIR)/,$(STAGE_COPY_FILES)) \
     $(addprefix $(STAGE_DIR)/lib/,$(STAGE_LIB_FILES)) \
     $(STAGE_XCLBIN_FILE_U50) \
     $(STAGE_XCLBIN_FILE_U55C) \
 	$(STAGE_XILINX_APPS_COMMON) \
-	$(STAGE_XCLBIN_FILE_F1) 
+	$(STAGE_XCLBIN_FILE_F1) \
+	$(STAGE_XCLBIN_FILE_U200) 
 #    $(STAGE_DIR)/$(STAGE_EXAMPLE_ZIP) \
 
 .PHONY: stage stage2
@@ -591,9 +706,6 @@ examples/python/run.sh: VERSION
 	sed -i 's,/cosinesim/1.2/xclbin,/cosinesim/$(PRODUCT_VER)/xclbin,g' src/cosinesim.cpp
 
 update-version : examples/python/run.sh
-
-# Common targets for all products (packaging)
-include ../common/Makefile-common.mk
 
 #######################################################################################################################
 #
@@ -614,16 +726,15 @@ help: help-common
 	@echo "  make doxy-cpp "
 	@echo "      Generate CPP documentation using doxygen. The default html output directory is ./build/cppdocs"
 	@echo ""
-	@echo "  make run [numDevices=1] [iterations=1] [numVectors=5000] [deviceNames=xilinx_u50_gen3x16_xdma_201920_3]"
+	@echo "  make run [numDevices=1] [iterations=1] [numVectors=5000] [deviceNames=u50]"
 	@echo "      Run standalone test with statically linked executable. numDevices, numVectors, and iterations are optional."
 	@echo "      Supported deviceNames: "
-	@echo "      xilinx_u50_gen3x16_xdma_201920_3"
-	@echo "      xilinx_u55c_gen3x16_xdma_base_2"
-	@echo "      xilinx_aws-vu9p-f1_shell-v04261818_201920_2"
+	@echo "        u50 (default)"
+	@echo "        u55c"
+	@echo "        aws-f1"
+	@echo "        u200"
+	@echo " "
+	@echo "  make run-staging-cpp"
+	@echo "      Run the CPP example from the staging area"	
 	@echo ""
-	@echo "  make xclbin DEVICE=<FPGA platform>"
-	@echo "      Build xclbin file targetting specified device. Vitis tool and PLATFORM_REPO_PATHS must be set to make xclbin."
-	@echo "      Supported devices:"
-	@echo "      xilinx_u50_gen3x16_xdma_201920_3 (Vitis 2020.2)"
-	@echo "      xilinx_u55c_gen3x16_xdma_2_202110_1 (Vitis 2021.2)"
-	@echo "      xilinx_aws-vu9p-f1_shell-v04261818_201920_2"
+
